[package]
name = "mutagen-derive"
version = "0.1.0"
authors = ["CodeBunny", "Patrick Chieppe <patrick.chieppe@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.0"
proc-macro2 = "1.0.8"
syn = { version = "1.0.72", features = ["full"] }
quote = "1.0.9"
